name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore Package
      run: nuget restore BattleNavHelper.sln 
    - name: Setup MSBuild.exe
      uses: microsoft/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild BattleNavHelper.sln
    - run: mkdir -p BattleNavHelper/bin/build

    - run: echo hello > BattleNavHelper/bin/build/BattleNavHelper.exe

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: BattleNavHelper/bin/build/BattleNavHelper.exe
