name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore Package
      run: nuget restore BattleNavHelper.sln 
    - name: Setup MSBuild.exe
      uses: microsoft/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild BattleNavHelper.sln
    - run: mkdir staging && cp bin/Debug/*.exe staging
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging
